### ISSUE TITLE
HttpMethodAnalyzer not compatible with Interpreter runtime

### ISSUE THREAD

**Issue by jonian** [DmitryTsepelev/graphql-ruby-persisted_queries#32]
When using HTTP Caching with `verify_http_method: true`, I get the error below.

Error log:
```
NoMethodError (undefined method `new' for #<GraphQL::PersistedQueries::HttpMethodAnalyzer:0x0000559aff07f540>):
  
graphql (1.10.5) lib/graphql/analysis/ast.rb:58:in `block (2 levels) in analyze_query'
graphql (1.10.5) lib/graphql/analysis/ast.rb:58:in `map'
graphql (1.10.5) lib/graphql/analysis/ast.rb:58:in `block in analyze_query'
graphql (1.10.5) lib/graphql/tracing.rb:67:in `block in trace'
graphql (1.10.5) lib/graphql/tracing.rb:81:in `call_tracers'
graphql (1.10.5) lib/graphql/tracing.rb:67:in `trace'
graphql (1.10.5) lib/graphql/analysis/ast.rb:56:in `analyze_query'
graphql (1.10.5) lib/graphql/analysis/ast.rb:32:in `block (2 levels) in analyze_multiplex'
graphql (1.10.5) lib/graphql/analysis/ast.rb:30:in `map'
graphql (1.10.5) lib/graphql/analysis/ast.rb:30:in `block in analyze_multiplex'
graphql (1.10.5) lib/graphql/tracing.rb:67:in `block in trace'
graphql (1.10.5) lib/graphql/tracing.rb:81:in `call_tracers'
graphql (1.10.5) lib/graphql/tracing.rb:67:in `trace'
graphql (1.10.5) lib/graphql/analysis/ast.rb:29:in `analyze_multiplex'
graphql (1.10.5) lib/graphql/execution/multiplex.rb:195:in `block in instrument_and_analyze'
graphql (1.10.5) lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
graphql (1.10.5) lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
graphql (1.10.5) lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
graphql (1.10.5) lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
graphql (1.10.5) lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
graphql (1.10.5) lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
graphql (1.10.5) lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
graphql (1.10.5) lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
graphql (1.10.5) lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
graphql (1.10.5) lib/graphql/execution/multiplex.rb:175:in `instrument_and_analyze'
graphql (1.10.5) lib/graphql/execution/multiplex.rb:61:in `block in run_queries'
graphql (1.10.5) lib/graphql/tracing.rb:67:in `block in trace'
graphql (1.10.5) lib/graphql/tracing.rb:81:in `call_tracers'
graphql (1.10.5) lib/graphql/tracing.rb:67:in `trace'
graphql (1.10.5) lib/graphql/execution/multiplex.rb:59:in `run_queries'
graphql (1.10.5) lib/graphql/execution/multiplex.rb:49:in `run_all'
graphql (1.10.5) lib/graphql/schema.rb:1575:in `multiplex'
graphql-persisted_queries (0.5.0) lib/graphql/persisted_queries/multiplex_resolver.rb:42:in `perform_multiplex'
graphql-persisted_queries (0.5.0) lib/graphql/persisted_queries/multiplex_resolver.rb:15:in `resolve'
graphql-persisted_queries (0.5.0) lib/graphql/persisted_queries/schema_patch.rb:52:in `multiplex'
graphql (1.10.5) lib/graphql/schema.rb:1546:in `execute'
```
The `GraphQL::Analysis::AST` plugin, that is required to use `GraphQL::Execution::Interpreter` expects analyzers to be classes and not instances as can be seen [here](https://github.com/rmosolgo/graphql-ruby/blob/5bbf21776e01f2cd1e83f63598f15dd935400b89/lib/graphql/analysis/ast.rb#L55) and `graphql-persisted-queries` creates instances [here](https://github.com/DmitryTsepelev/graphql-ruby-persisted_queries/blob/fdcf6698028df423c8fd7799e1d13edc5b1ca2dd/lib/graphql/persisted_queries/schema_patch.rb#L35). 

The AST analyzers  seem to have a different interface from plain analyzers and I think a separate analyzer that inherits [GraphQL::Analysis::AST::Analyzer](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/analysis/ast/analyzer.rb) is needed.

**Comment by DmitryTsepelev** [comment]
Thanks for the report! Fixed as part of #33, do you have a chance to try it out before I merge it in?

**Comment by jonian** [comment]
Thank you for the quick response!

I tested with/without interpreter runtime and it works without problems.

**Comment by DmitryTsepelev** [comment]
Version 0.5.1 is on its way
